#!/usr/bin/env bash
# Configures an Nginx server to redirect to another page

apt-get update
apt-get install -y nginx

mkdir /etc/ngix/html
touch /etc/ngix/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
  listen 80;
  listen [::]:80 default_server;
  root /etc/nginx/html;
  index index.html index.htm;
  location /redirect_me {
      return 301 http://cuberule.com/;
  }
}" > /etc/nginx/sites-available/default
service nginx restart
