#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend myfrontend
    bind 0:80
    default_backend servers
backend servers
    balance roundrobin
    server 296451-web-01 100.27.14.120:80 check
    server 296451-web-02 54.174.217.169:80 check

EOF

sudo systemctl restart haproxy
