#!/usr/bin/env bash
# Bash script that loops from 1 to 10

count=0
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		printf "bad luck\n"
	elif [ $count -eq 8 ]
	then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
	((count++))
done
