#!/usr/bin/env bash
# prints Best School using case

count=1
while [ $count -le 20 ]
do
	case $count in

		4)
			printf "%d\n" $count
			printf "bad luck from China\n"
			;;	
		9)
			printf "%d\n" $count
			printf "bad luck from Japan\n"
			;;
		17)
			printf "%d\n" $count
			printf "bad luck from Italy\n"
			;;
		*)
			printf "%d\n" $count
			;;
	esac
	((count++))
done
