#!/usr/bin/env bash

# script that display the content of the current directory

for file in *
do
	if [[ -f $file ]]
	then
		# Extract the part of the name after the first dash
		names=$(echo "$file" | cut -d'-' -f2-)
		echo "$names"
	fi
done
