#!/usr/bin/env bash
# Use ssh single character flag to connect to your server using the private key
# key ~/.ssh/school with the user ubuntu.
# Username: ubuntu
ssh -i ~/.ssh/school ubuntu@eadb1d0dfb7c.e93e7bb8.alx-cod.online
