#!/usr/bin/env bash
# Use ssh single character flag to connect to your server using the private key
# key ~/.ssh/school with the user ubuntu.
# Username: ubuntu
# Server details
server_ip="54.174.217.169"
user="ubuntu"
private_key="~/.ssh/school"

# SSH connection using a single character flag
ssh -i "$private_key" "$user"@"$server_ip"
